firefox:
    extensions:
        Behat\MinkExtension:
            browser_name: firefox
            selenium2:
                capabilities: {"browser": "firefox"}
chrome:
    extensions:
        Behat\MinkExtension:
            browser_name: chrome
            selenium2:
                capabilities: {"browser": "chrome"}
