#!/bin/bash

case "$1" in
    'start')
        if test -f /tmp/selenium.pid
        then
            echo "Selenium is already running."
        else
            rm -f /tmp/.X*lock;
            xvfb-run -n 99 --server-args="-screen 0 1280x800x24 -ac +extension RANDR" \
              java -jar /opt/selenium/selenium-server-standalone.jar > /var/log/selenium_output.log 2> /var/log/selenium_error.log & echo $! > /tmp/selenium.pid
            error=$?
            if test $error -gt 0
            then
                echo "Error $error! Couldn't start Selenium!"
            fi
        fi
    ;;
    'stop')
        if test -f /tmp/selenium.pid
        then
            echo "Stopping Selenium..."
            PID=`cat /tmp/selenium.pid`
            kill -3 $PID
            if kill -9 $PID ;
                then
                    sleep 2
                    test -f /tmp/selenium.pid && rm -f /tmp/selenium.pid
                else
                    echo "Selenium could not be stopped..."
                fi
        else
            echo "Selenium is not running."
        fi
        ;;
    *)
        echo "Usage: $SELF start|stop"
        exit 1
    ;;
esac
